name: CD

on:
  push:
    tags: 'v*'

jobs:     
  release-linux:
    uses: francoisbonneau/actions/.github/workflows/cd-linux.yml@master
    with:
      name: OPENGEODE_MYMODULE
      repos: OpenGeode
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

  release-linux-python:
    uses: francoisbonneau/actions/.github/workflows/cd-linux-python.yml@master
    with:
      name: OPENGEODE_MYMODULE
      repos: OpenGeode
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

  release-windows:
    uses: francoisbonneau/actions/.github/workflows/cd-windows.yml@master
    with:
      name: OPENGEODE_MYMODULE
      repos: OpenGeode
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

  release-windows-python:
    uses: francoisbonneau/actions/.github/workflows/cd-windows-python.yml@master
    with:
      name: OPENGEODE_MYMODULE
      repos: OpenGeode
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
