name: CD

on:
  push:
    tags: 'v*'

jobs:     
  release-linux:
    uses: francoisbonneau/my_actions/.github/workflows/opengeode_cd_linux.yml@master
    with:
      name: OPENGEODE_MYMODULE
      repos: OpenGeode
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

  release-linux-python:
    uses: francoisbonneau/my_actions/.github/workflows/opengeode_cd_linux_python.yml@master
    with:
      name: OPENGEODE_MYMODULE
      repos: OpenGeode
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

  release-windows:
    uses: francoisbonneau/my_actions/.github/workflows/opengeode_cd_windows.yml@master
    with:
      name: OPENGEODE_MYMODULE
      repos: OpenGeode
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

  release-windows-python:
    uses: francoisbonneau/my_actions/.github/workflows/opengeode_cd_windows_python.yml@master
    with:
      name: OPENGEODE_MYMODULE
      repos: OpenGeode
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
